
game_types = [
    "Horror",
    "RPG (Role-Playing Game)",
    "Action",
    "Platformers",
    "Strategy",
    "Racing",
    "Adventure",
    "Simulators",
    "Sports",
    "Music",
    "Fighting",
    "Puzzle",
    "Economic",
    "Survival",
    "MMORPG (Massively Multiplayer Online Role-Playing Game)",
    "TPS (Third-Person Shooter)",
    "FPS (First-Person Shooter)",
    "MOBA (Multiplayer Online Battle Arena)",
    "TPS (Tactical Shooter)",
    "Card Games"
]
game_themes = [
    "Detective",
    "Medieval",
    "Sci-Fi Future",
    "Post-Apocalyptic",
    "Fantasy",
    "Space",
    "Historical",
    "Military",
    "Horror",
    "Superheroes",
    "Ancient World",
    "Crime",
    "Movie",
    "Animal World",
    "Surreal",
    "Fairy Tale",
    "Zombies",
    "Political Intrigue",
    "Cute and Charming",
    "Steampunk",
    "Ancient japan",
    "Western",
    "Educational",
    "Environmental",
    "Music",
    "Underwater",
    "World War",
    "Myths and Legends",
    "Jungle Adventure",
    "Sports",
    "Time Travel",
    "Dinosaurs",
    "Alien Invasion",
    "Desert Rally",
    "Love Story",
    "Family and Monsters",
    "Magical World",
    "Thriller",
    "Noir Adventure",
    "Action Movie",
    "Sports Competition",
    "Nature and Ecology",
    "Puzzles",
    "Cars and Racing",
    "Sea Battle",
    "New York",
    "Rescuers",
    "Survival on Deserted Island",
    "Virtual Reality",
    "Military Game",
    "Special Operation",
    "World Replica",
]

game_dimension = [
                "2D",
                "3D"
]
game_goals = [
    "Acquire a legendary weapon",
    "Defeat all the bosses",
    "Discover a mysterious realm",
    "Build a powerful base",
    "Complete the main storyline",
    "Achieve all achievements",
    "Maximize character development",
    "Win a tournament or sports competition",
    "Solve logical puzzles",
    "Uncover all hidden locations",
    "Create your own city or civilization",
    "Save the world from a threat",
    "Reach the highest skill level",
    "Outperform other players in competition",
    "Find all collectible items",
    "Attain the title of king or queen",
    "Establish a legendary alliance or gang",
    "Complete an exploration challenge",
    "Create and maintain a healthy ecosystem",
    "Survive as long as possible in challenging conditions",
    "Obtain a rare and unique mount or vehicle",
    "Master a complex crafting system",
    "Collect a set of rare artifacts",
    "Become a renowned and respected hero",
    "Defend a stronghold against invaders",
    "Solve a murder mystery",
    "Uncover the truth behind a conspiracy",
    "Achieve a high score or ranking",
    "Rescue a kidnapped character or ally",
    "Win a strategic war or battle",
    "Lead a rebellion against tyranny",
    "Build a successful business or empire",
    "Complete a time-sensitive mission",
    "Survive a zombie apocalypse",
    "Navigate a maze or labyrinth",
    "Retrieve a stolen artifact",
    "Solve a series of riddles",
    "Defeat a rival or nemesis",
    "Escape from a dangerous situation",
    "Obtain a hidden treasure",
    "Discover the origins of a mysterious power"
]
